name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정 (UTC) 실행
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: bocastle
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
